-- V2: subscription_request
-- One row per investor request within an optimization run, with its accept/reject outcome.

CREATE TABLE subscription_request (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           UUID           NOT NULL,
    investor_name    VARCHAR(255)   NOT NULL,
    requested_amount NUMERIC(19, 2) NOT NULL,
    fee_revenue      NUMERIC(19, 2) NOT NULL,
    accepted         BOOLEAN        NOT NULL,
    input_index      INTEGER        NOT NULL,

    CONSTRAINT fk_subscription_request_run
        FOREIGN KEY (run_id) REFERENCES optimization_run (id) ON DELETE CASCADE,
    CONSTRAINT chk_subscription_amounts_non_negative
        CHECK (requested_amount >= 0 AND fee_revenue >= 0)
);

CREATE INDEX idx_subscription_request_run_id
    ON subscription_request (run_id);